import os
from rsf.proj import *

########################################################################
# RETRIEVE DATA
########################################################################
# define SLIM FTP server information
FTPserver = {
        'server': 'slim.eos.ubc.ca',
        'login': 'ftp',
        'password':''}
# actuall ftp://slim.eos.ubc.ca/data/SoftwareRelease/Modeling/3DAcousticFreqModeling/data

loc = os.path.join('SoftwareRelease','Modeling','3DAcousticFreqModeling','data')
files = [ 'Dobs.rsf','m_init.rsf','m_true.rsf' ]
# fetch data from FTP server
for elm in files:
        Fetch(elm,loc,FTPserver)


