import os
from rsf.proj import *

########################################################################
# RETRIEVE DATA
########################################################################
# define SLIM FTP server information
FTPserver = {
        'server': 'slim.eos.ubc.ca',
        'login': 'ftp',
        'password':''}

loc   = os.path.join('SoftwareRelease','WaveformInversion','TimeLapseFWI','data')
files = ['BG_timelapse_model.mat','ObsData.mat']
# fetch data from FTP server
for elm in files:
        Fetch(elm,loc,FTPserver)


